# Q1: In this question you have to scrape data using the filters available on the webpage You have to use the location and 
salary filter. 
You have to scrape data for “Data Scientist” designation for first 10 job results. 
You have to scrape the job-title, job-location, company name, experience required. 
The location filter to be used is “Delhi/NCR”. The salary filter to be used is “3-6” lakhs 
The task will be done as shown in the below steps: 
1. first get the web page https://www.naukri.com/
2. Enter “Data Scientist” in “Skill, Designations, and Companies” field. 
3. Then click the search button. 
4. Then apply the location filter and salary filter by checking the respective boxes 
5. Then scrape the data for the first 10 jobs results you get. 
6. Finally create a dataframe of the scraped data.

In [9]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings  
warnings.filterwarnings('ignore') #ignore unnecessary warnings
from selenium.webdriver.common.by import By #coding and text purpose

In [10]:
driver=webdriver.Chrome()

In [11]:
# opening the naukari page on automated chrome window
driver.get("http://www.naukri.com/")

In [12]:
# entering designation and location and salary
designation=driver.find_element(By.CLASS_NAME,"suggestor-input ")
designation.send_keys('Data Scientist')

In [13]:
search=driver.find_element(By.CLASS_NAME,"qsbSubmit")
search.click()

In [16]:
location=driver.find_element(By.XPATH,"/html/body/div/div/main/div[1]/div[1]/div/div/div[2]/div[2]/div[2]/div[3]/label/i")
location.click()

In [15]:
salary=driver.find_element(By.XPATH,"/html/body/div/div/main/div[1]/div[1]/div/div/div[2]/div[6]/div[2]/div[2]/label/i")
salary.click()

In [17]:
job_title=driver.find_elements(By.XPATH,'//div[@class=" row1"]/a')
job_title

[<selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7048")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7131")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7210")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7291")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7347")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7406")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7462")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7521")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7587")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7663")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7741")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7813")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7939")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8017")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8093")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8169")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8247")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8306")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8385")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8461")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8539")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8606")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8684")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8760")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8836")>]

In [18]:
job_titles=[]
for i in job_title:
    job_titles.append(i.text)
    
job_titles[:10]

['Data Scientist',
 'Data Scientist',
 'Lead Data Scientist',
 'Data Scientist',
 'Sr. Data Scientist',
 '',
 '',
 '',
 'Data Scientist',
 'Lead Customer Success - Data Scientist']

In [19]:
#scraping location from web page
job_location=driver.find_elements(By.XPATH,'//span[@class="locWdth"]')
job_location

[<selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7081")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7164")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7230")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7618")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7696")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7768")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7846")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7972")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8048")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8124")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8202")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8267")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8339")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8416")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8494")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8561")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8639")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8715")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8791")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8867")>]

In [20]:
job_locations=[]
for i in job_location:
  job_locations.append(i.text)
job_locations[:10]

['Mumbai, Hyderabad, Gurugram',
 'Gurugram, Bengaluru',
 'Kolkata, Mumbai, New Delhi, Hyderabad/Secunderabad, Pune, Chennai, Bangalore/Bengaluru',
 'Kolkata, Mumbai, New Delhi, Hyderabad, Pune, Chennai, Bengaluru',
 'Pune, Gurugram',
 'Noida, Mumbai, Pune',
 'Noida',
 'Noida',
 'Hyderabad, New Delhi, Pune, Gurugram, Bengaluru',
 'Gurugram, Bengaluru']

In [23]:
#scraping company name from web page
company_tags=driver.find_elements(By.XPATH,'//a[@class=" comp-name mw-25"]')
company_tags

[<selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7053")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7136")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7590")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7668")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7818")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.7944")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8020")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8096")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8174")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8311")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8388")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8466")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8611")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8687")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8763")>,
 <selenium.webdriver.remote.webelement.WebElement (session="cd47e973603902f86de2a3ece4502ba1", element="f.B497D0E7D24C740BA21B2A2FA865D80C.d.CB8C4CB7C742C2DF11D55809A7802B8A.e.8839")>]

In [25]:
company_name=[]
for i in company_tags:
 company_name.append(i.text)
company_name[:10]

['Deloitte',
 'Blackbuck',
 'Fort Technologies',
 'ZS Associates',
 'Innovaccer',
 'Times Internet',
 'The Scholar',
 'Acenet',
 'Searchurcollege',
 'Gartner']

In [26]:
#scraping experience from web page
exp_tags=driver.find_elements(By.XPATH,'//span[@class="expwdth"]')
experience=[]
for i in exp_tags:
 experience.append(i.text)
experience[:10]

['3-6 Yrs',
 '3-7 Yrs',
 '3-7 Yrs',
 '1-3 Yrs',
 '2-4 Yrs',
 '4-7 Yrs',
 '2-7 Yrs',
 '3-8 Yrs',
 '3-8 Yrs',
 '3-4 Yrs']

In [27]:
print(len(job_titles[:10]),len(job_locations[:10]),len(company_name[:10]),len(experience[:10]))

10 10 10 10

In [28]:
import pandas as pd
df=pd.DataFrame({'Title':job_titles[:10],'Location':job_locations[:10],'Company_name': company_name[:10],'Experience':experience[:10]})
df

,Title,Location,Company_name,Experience
0,Data Scientist,"Mumbai, Hyderabad, Gurugram",Deloitte,3-6 Yrs
1,Data Scientist,"Gurugram, Bengaluru",Blackbuck,3-7 Yrs
2,Lead Data Scientist,"Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Fort Technologies,3-7 Yrs
3,Data Scientist,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",ZS Associates,1-3 Yrs
4,Sr. Data Scientist,"Pune, Gurugram",Innovaccer,2-4 Yrs
5,,"Noida, Mumbai, Pune",Times Internet,4-7 Yrs
6,,Noida,The Scholar,2-7 Yrs
7,,Noida,Acenet,3-8 Yrs
8,Data Scientist,"Hyderabad, New Delhi, Pune, Gurugram, Bengaluru",Searchurcollege,3-8 Yrs
9,Lead Customer Success - Data Scientist,"Gurugram, Bengaluru",Gartner,3-4 Yrs

Q2: Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You have to scrape the 
job-title, job-location, company_name, experience_required. You have to scrape first 10 jobs data.
This task will be done in following steps:
1. First get the webpage https://www.shine.com/
2. Enter “Data Analyst” in “Job title, Skills” field and enter “Bangalore” in “enter the location” field.
3. Then click the searchbutton. 
4. Then scrape the data for the first 10 jobs results you get. 
5. Finally create a dataframe of the scraped data.

In [60]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By #coding and text purpose

In [61]:
driver=webdriver.Chrome()

In [62]:
# opening the shine page on automated chrome window
driver.get("http://www.shine.com/")

In [63]:
search=driver.find_element(By.XPATH,'/html/body/div/header/div[3]/div/div/div[1]/div/span/i')
search.click()

In [64]:
designation=driver.find_element(By.CLASS_NAME,'form-control  ')
designation.send_keys('Data Analyst')

In [65]:
location=driver.find_element(By.XPATH,'/html/body/div/div[4]/div/div[2]/div[2]/div/form/div/div[1]/ul/li[2]/div/input')
location.send_keys('Bangalore')

In [66]:
search=driver.find_element(By.XPATH,'/html/body/div/div[4]/div/div[2]/div[2]/div/form/div/div[2]/div/button')
search.click()

In [89]:
job_title=driver.find_elements(By.XPATH,'//h2[@itemprop="name"]/a')
job_title[:10]

[<selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15300")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15346")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15499")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15501")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15503")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15504")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15505")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15506")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15507")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15508")>]

In [90]:
job_titles=[]
for i in job_title[:10]: 
    job_titles.append(i.text)
    
job_titles[:10]

['Data Analyst',
 'Clinical Data Analyst',
 'Data Analyst',
 'Hiring For Data Analyst',
 'Clinical Data Analyst',
 'Lead Data Analyst',
 'Data Analyst',
 'Technical Data Architect',
 'Oracle Utilities (customer care & Billing) CC&B Busines ...',
 'Clinical Data Associate']

In [94]:
job_location=driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard_lists__fdnsc"]/div[2]')
job_location[:10]

[<selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.13112")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.13114")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15542")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15543")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15544")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15545")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15546")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15547")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15548")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15549")>]

In [97]:
job_locations=[]
for i in job_location[:10]:
    job_locations.append(i.text)
    
job_locations[:10]

['Bangalore\n+9',
 'Bangalore\n+6',
 'Bangalore\n+9',
 'Bangalore\n+12',
 'Bangalore\n+6',
 'Bangalore',
 'Bangalore\n+3',
 'Bangalore',
 'Bangalore\n+2',
 'Bangalore\n+6']

In [98]:
company_name=driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard_cName__mYnow"]/span')
company_name[:10]

[<selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15560")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15564")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15565")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15566")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15567")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15568")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15569")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15570")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15571")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15572")>]

In [100]:
company_names=[]
for i in company_name[:10]:
    company_names.append(i.text) 
    
company_names[:10]

['sahast sales corporation',
 'techno endura',
 'sahast sales corporation',
 'radhika enterprises',
 'techno endura',
 'ara resources private limited',
 'diraa hr services hiring for mncs',
 'uprighthc solutions private limited',
 'ltimindtree limited',
 'techno endura']

In [101]:
experience=driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard_lists__fdnsc"]/div[1]')
experience[:10]

[<selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.13111")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.13113")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15583")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15584")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15585")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15586")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15587")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15588")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15589")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2290eb151d9c24836efb4b4a838425fe", element="f.FB305E4C2A25FA37DFF8BD7D53AC6C2C.d.7C36044C4665B43968856E4D83E10FFD.e.15590")>]

In [102]:
experience_required=[]
for i in experience[:10]:
    experience_required.append(i.text)
    
experience_required[:10]

['12 to 22 Yrs',
 '0 to 1 Yr',
 '12 to 22 Yrs',
 '0 to 4 Yrs',
 '0 to 1 Yr',
 '4 to 9 Yrs',
 '0 to 1 Yr',
 '10 to 20 Yrs',
 '5 to 9 Yrs',
 '0 to 1 Yr']

In [103]:
df=pd.DataFrame({'Title':job_titles[:10],'Location':job_locations[:10],'Company_name': company_names[:10],'Experience':experience_required[:10]})
df

,Title,Location,Company_name,Experience
0,Data Analyst,Bangalore\n+9,sahast sales corporation,12 to 22 Yrs
1,Clinical Data Analyst,Bangalore\n+6,techno endura,0 to 1 Yr
2,Data Analyst,Bangalore\n+9,sahast sales corporation,12 to 22 Yrs
3,Hiring For Data Analyst,Bangalore\n+12,radhika enterprises,0 to 4 Yrs
4,Clinical Data Analyst,Bangalore\n+6,techno endura,0 to 1 Yr
5,Lead Data Analyst,Bangalore,ara resources private limited,4 to 9 Yrs
6,Data Analyst,Bangalore\n+3,diraa hr services hiring for mncs,0 to 1 Yr
7,Technical Data Architect,Bangalore,uprighthc solutions private limited,10 to 20 Yrs
8,Oracle Utilities (customer care & Billing) CC&...,Bangalore\n+2,ltimindtree limited,5 to 9 Yrs
9,Clinical Data Associate,Bangalore\n+6,techno endura,0 to 1 Yr

Q3: Scrape 100 reviews data from flipkart.com for iphone11 phone. You have to go the link: 
https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&marketplace=FLIPKART
As shown in the above page you have to scrape the tick marked attributes. These are:
1. Rating
2. Review summary
3. Full review
4. You have to scrape this data for first 100reviews.

In [10]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By #coding and text purpose
import time

In [2]:
driver=webdriver.Chrome()

In [4]:
# opening the shine page on automated chrome window
driver.get('https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&marketplace=FLIPKART')

In [7]:
rating=driver.find_elements(By.XPATH,'//div[@class="_3LWZlK _1BLPMq"]')
#rating[:10]

[<selenium.webdriver.remote.webelement.WebElement (session="7bdb29e6685775a7836ad7f706398279", element="f.C026199F860A19AE9505AF6129F31E3F.d.C33D96CCD0D076CDAFBC4733340448AB.e.79")>,
 <selenium.webdriver.remote.webelement.WebElement (session="7bdb29e6685775a7836ad7f706398279", element="f.C026199F860A19AE9505AF6129F31E3F.d.C33D96CCD0D076CDAFBC4733340448AB.e.171")>,
 <selenium.webdriver.remote.webelement.WebElement (session="7bdb29e6685775a7836ad7f706398279", element="f.C026199F860A19AE9505AF6129F31E3F.d.C33D96CCD0D076CDAFBC4733340448AB.e.178")>,
 <selenium.webdriver.remote.webelement.WebElement (session="7bdb29e6685775a7836ad7f706398279", element="f.C026199F860A19AE9505AF6129F31E3F.d.C33D96CCD0D076CDAFBC4733340448AB.e.187")>,
 <selenium.webdriver.remote.webelement.WebElement (session="7bdb29e6685775a7836ad7f706398279", element="f.C026199F860A19AE9505AF6129F31E3F.d.C33D96CCD0D076CDAFBC4733340448AB.e.211")>,
 <selenium.webdriver.remote.webelement.WebElement (session="7bdb29e6685775a7836ad7f706398279", element="f.C026199F860A19AE9505AF6129F31E3F.d.C33D96CCD0D076CDAFBC4733340448AB.e.212")>,
 <selenium.webdriver.remote.webelement.WebElement (session="7bdb29e6685775a7836ad7f706398279", element="f.C026199F860A19AE9505AF6129F31E3F.d.C33D96CCD0D076CDAFBC4733340448AB.e.213")>,
 <selenium.webdriver.remote.webelement.WebElement (session="7bdb29e6685775a7836ad7f706398279", element="f.C026199F860A19AE9505AF6129F31E3F.d.C33D96CCD0D076CDAFBC4733340448AB.e.206")>,
 <selenium.webdriver.remote.webelement.WebElement (session="7bdb29e6685775a7836ad7f706398279", element="f.C026199F860A19AE9505AF6129F31E3F.d.C33D96CCD0D076CDAFBC4733340448AB.e.214")>,
 <selenium.webdriver.remote.webelement.WebElement (session="7bdb29e6685775a7836ad7f706398279", element="f.C026199F860A19AE9505AF6129F31E3F.d.C33D96CCD0D076CDAFBC4733340448AB.e.215")>]

In [15]:
ratings=[]
review_summary=[]
full_review=[]

In [16]:
for page in range(10):
    rating=driver.find_elements(By.XPATH,'//div[@class="_3LWZlK _1BLPMq"]')
    review=driver.find_elements(By.XPATH,'//p[@class="_2-N8zT"]')
    review_full=driver.find_elements(By.XPATH,'//div[@class="t-ZTKy"]/div/div')
    
    for i in rating:
     ratings.append(i.text)
    ratings[:100]
    
    for i in review:
     review_summary.append(i.text)
    review_summary[:100]
    
    for i in review_full:
     full_review.append(i.text)
    full_review[:100]
    
    
     #next_button=driver.find_element(By.XPATH,'/html/body/div/div/div[3]/div/div/div[2]/div[13]/div/div/nav/a[11]/span')
     #next_button.click()
    #time.sleep(10)

In [17]:
ratings[:100]

['5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5']

In [18]:
print(len(ratings[:100]),len(review_summary[:100]),len(full_review[:100]))

100 100 100

In [19]:
df=pd.DataFrame({'Ratings':ratings[:100],'Review summary':review_summary[:100],'Review':full_review[:100]})
df

,Ratings,Review summary,Review
0,5,Classy product,Camera is awesome\nBest battery backup\nA perf...
1,5,Best in the market!,Good Camera
2,5,Worth every penny,Feeling awesome after getting the delivery of ...
3,5,Wonderful,This is amazing at all
4,5,Fabulous!,Super🔥 and good performance 👌❤️
...,...,...,...
95,5,Terrific,Very very good
96,5,Perfect product!,Photos super
97,5,Terrific purchase,Value for money 😍
98,5,Just wow!,Perfect Product!!
99,5,Brilliant,very good camera quality

Q4: Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the search field.
You have to scrape 3 attributes of each sneaker:
1. Brand
2. Product Description
3. Price

In [20]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By

In [22]:
driver=webdriver.Chrome()

In [23]:
driver.get('https://www.flipkart.com')

In [24]:
product=driver.find_element(By.CLASS_NAME,'Pke_EE')
product.send_keys('sneakers')

In [26]:
search=driver.find_element(By.CLASS_NAME,'_2iLD__')
search.click()

In [27]:
brand=driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
#brand[:10]

[<selenium.webdriver.remote.webelement.WebElement (session="62c4e2ec3c1d07daa044812a3fedaa7d", element="f.DBA38AAB34B20919C928B9746F9CE432.d.B3EC7AAF2937787AB14324CFA86474A6.e.4259")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62c4e2ec3c1d07daa044812a3fedaa7d", element="f.DBA38AAB34B20919C928B9746F9CE432.d.B3EC7AAF2937787AB14324CFA86474A6.e.4291")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62c4e2ec3c1d07daa044812a3fedaa7d", element="f.DBA38AAB34B20919C928B9746F9CE432.d.B3EC7AAF2937787AB14324CFA86474A6.e.4322")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62c4e2ec3c1d07daa044812a3fedaa7d", element="f.DBA38AAB34B20919C928B9746F9CE432.d.B3EC7AAF2937787AB14324CFA86474A6.e.4353")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62c4e2ec3c1d07daa044812a3fedaa7d", element="f.DBA38AAB34B20919C928B9746F9CE432.d.B3EC7AAF2937787AB14324CFA86474A6.e.4386")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62c4e2ec3c1d07daa044812a3fedaa7d", element="f.DBA38AAB34B20919C928B9746F9CE432.d.B3EC7AAF2937787AB14324CFA86474A6.e.4417")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62c4e2ec3c1d07daa044812a3fedaa7d", element="f.DBA38AAB34B20919C928B9746F9CE432.d.B3EC7AAF2937787AB14324CFA86474A6.e.4451")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62c4e2ec3c1d07daa044812a3fedaa7d", element="f.DBA38AAB34B20919C928B9746F9CE432.d.B3EC7AAF2937787AB14324CFA86474A6.e.4483")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62c4e2ec3c1d07daa044812a3fedaa7d", element="f.DBA38AAB34B20919C928B9746F9CE432.d.B3EC7AAF2937787AB14324CFA86474A6.e.4516")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62c4e2ec3c1d07daa044812a3fedaa7d", element="f.DBA38AAB34B20919C928B9746F9CE432.d.B3EC7AAF2937787AB14324CFA86474A6.e.4547")>]

In [28]:
brands=[]
product=[]
prices=[]

In [31]:
for page in range(3):
    brand=driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
    product_des=driver.find_elements(By.XPATH,'//a[@class="IRpwTa"]')
    price=driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]')
    
    for i in brand:
        brands.append(i.text)
        brands[:100]
        
    for i in product_des:
        product.append(i.text)
        product[:100]
        
    for i in price:
        prices.append(i.text)
        prices[:100]

In [32]:
brands[:100]

['HOTSTYLE',
 'BRUTON',
 'Deals4you',
 'URBANBOX',
 'RED TAPE',
 'BIRDE',
 'BRUTON',
 'BRUTON',
 'aadi',
 'RED TAPE',
 'BRUTON',
 'BRUTON',
 'BRUTON',
 'asian',
 'RED TAPE',
 'HIGHLANDER',
 'Deals4you',
 'BRUTON',
 'Shozie',
 'HOTSTYLE',
 'BRUTON',
 'BRUTON',
 'WOODLAND',
 'HOTSTYLE',
 'RED TAPE',
 'BIRDE',
 'BRUTON',
 'Shozie',
 'BIRDE',
 'Ego by NS',
 'BRUTON',
 'BRUTON',
 'asian',
 'ADIDAS ORIGINALS',
 'Labbin',
 'RED TAPE',
 'ATOM',
 'BRUTON',
 'PUMA',
 'Layasa',
 'HOTSTYLE',
 'BRUTON',
 'Deals4you',
 'URBANBOX',
 'RED TAPE',
 'BIRDE',
 'BRUTON',
 'BRUTON',
 'aadi',
 'RED TAPE',
 'BRUTON',
 'BRUTON',
 'BRUTON',
 'asian',
 'RED TAPE',
 'HIGHLANDER',
 'Deals4you',
 'BRUTON',
 'Shozie',
 'HOTSTYLE',
 'BRUTON',
 'BRUTON',
 'WOODLAND',
 'HOTSTYLE',
 'RED TAPE',
 'BIRDE',
 'BRUTON',
 'Shozie',
 'BIRDE',
 'Ego by NS',
 'BRUTON',
 'BRUTON',
 'asian',
 'ADIDAS ORIGINALS',
 'Labbin',
 'RED TAPE',
 'ATOM',
 'BRUTON',
 'PUMA',
 'Layasa',
 'HOTSTYLE',
 'BRUTON',
 'Deals4you',
 'URBANBOX',
 'RED TAPE',
 'BIRDE',
 'BRUTON',
 'BRUTON',
 'aadi',
 'RED TAPE',
 'BRUTON',
 'BRUTON',
 'BRUTON',
 'asian',
 'RED TAPE',
 'HIGHLANDER',
 'Deals4you',
 'BRUTON',
 'Shozie',
 'HOTSTYLE']

In [ ]:
print(len(brands[:100]),len(product[:100]),len(prices[:100]))

In [33]:
df=pd.DataFrame({'Brands':brands[:100],'Product Description':product[:100],'Price':prices[:100]})
df

        Brands                                Product Description   Price
0     HOTSTYLE           Exclusive Sneaker Shoes Sneakers For Men    ₹294
1       BRUTON                                 Sneakers For Women    ₹296
2    Deals4you  Trending Stylish Casual Outdoor Shoes For Men ...    ₹439
3     URBANBOX  Casual Sneakers Shoes for Men | Soft Cushioned...    ₹299
4     RED TAPE      Combo Pack of 2 Casual Shoes Sneakers For Men  ₹1,179
..         ...                                                ...     ...
95  HIGHLANDER      Combo Pack of 2 Casual Shoes Sneakers For Men    ₹629
96   Deals4you      Modern Trendy Sneakers Shoes Sneakers For Men    ₹339
97      BRUTON  Carnival-02 Mens High Top Casual Chunky Sneake...    ₹299
98      Shozie                      FORUM 84 LOW Sneakers For Men    ₹399
99    HOTSTYLE  Casual Sneakers ColourFul Block Shoes For Boys...    ₹342

[100 rows x 3 columns]

Q5: Go to webpage https://www.amazon.in/ Enter “Laptop” in the search field and then click the search icon. Then set CPU Type filter to “Intel Core i7” as shown in the below image:
Aftersetting the filters scrape first 10 laptops data. You have to scrape 3 attributes for each laptop:
1. Title
2. Ratings
3. Price

In [43]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By

In [44]:
driver=webdriver.Chrome()

In [45]:
driver.get(' https://www.amazon.in/')

In [46]:
product=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input')
product.send_keys('Laptop')

In [47]:
search=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input')
search.click()

In [50]:
product_name=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/div[1]/div[2]/div/div[3]/span/div[1]/div/div/div[6]/ul[19]/span/span[10]/li/span/a/div/label/i')
product_name.click()

In [51]:
titles=[]
ratings=[]
prices=[]

In [53]:
title=driver.find_elements(By.XPATH,'//span[@class="a-size-medium a-color-base a-text-normal"]')
for i in title:
 titles.append(i.text)
 titles[:10]

rating=driver.find_elements(By.XPATH,'//span[@class="a-size-base s-underline-text"]')    
for i in rating:
 ratings.append(i.text)
ratings[:10]
 
price=driver.find_elements(By.XPATH,'//span[@class="a-price-whole"]')
for i in price:
 prices.append(i.text)
 prices[:10]

In [54]:
titles[:10]

['Lenovo IdeaPad Slim 3 Intel Core i7 12th Gen 15.6 inch (39.62cm) FHD Thin & Light Laptop (16GB/512GB SSD/Windows 11/Office 2021/3months Game Pass/Arctic Grey/1.63Kg), 82RK011EIN',
 'MSI Modern 14, Intel 12th Gen. i7-1255U, 36CM FHD 60Hz Laptop (16GB/512GB NVMe SSD/Windows 11 Home/Intel Iris Xe Graphics/Classic Black/1.4Kg), C12M-459IN',
 'MSI Modern 14, Intel 12th Gen. i7-1255U, 36CM FHD 60Hz Laptop (16GB/512GB NVMe SSD/Windows 11 Home/Intel Iris Xe Graphics/Classic Black/1.4Kg), C12M-459IN',
 'ASUS TUF Gaming F15, 15.6"(39.62 cms) FHD 144Hz, Intel Core i7-11800H 11th Gen, 4GB NVIDIA GeForce RTX 3050 Ti, Gaming Laptop (16GB/1TB SSD/Win 11/MSO/90WHrs Battery/Black/2.30 Kg), FX506HE-HN385WS',
 'Acer Travelmate Business Laptop Intel Core i7-11th Gen (Windows 11 Home/16 GB Ram/1TB SSD/Intel Iris Xe Graphics/14.0 IPS Display/Backlit Keyboard/Fingerprint Sensor) TMP214-53',
 'Lenovo Yoga Slim7 Carbon Intel Evo i7 1260P 13.3"(33.78cm) QHD 400Nit Touch Laptop(16GB/1TB SSD/Win 11/Office 2021/Backlit KB/IR Cam/3Yr Warranty/Alexa/3 Month Game Pass/Moon White/ 1kg),82U90080IN',
 'Lenovo IdeaPad Slim 3 Intel Core i7 12th Gen 15.6 inch (39.62cm) FHD Thin & Light Laptop (16GB/512GB SSD/Windows 11/Office 2021/3months Game Pass/Arctic Grey/1.63Kg), 82RK011EIN',
 'HP Pavilion X360 11th Gen Intel Core i7 14" (35.6cm) FHD Multitouch 2in1 Laptop (16Gb Ram/512Gb Ssd/B&O/Win 11 Home/FPR/Backlit Kb/Intel Iris Xe Graphics/Pen/Alexa/Ms Office/Silver/1.52Kg)14-Dy1047Tu',
 'ASUS Vivobook 15, Intel Core i7-12650H 12th Gen, 15.6" (39.62 cm) FHD, Thin and Light Laptop (16GB/512GB/Win11/Office 2021/Blue/1.7 kg), X1502ZA-EJ741WS',
 'Dell Inspiron 5430 Laptop, 13th Gen Intel Core i7-1360P Processor/16GB/1TB SSD/14.0" (35.56cm) FHD+ WVA 250 nits/Backlit KB + FPR/Win 11 + MSO\'21/15 Month McAfee/Platinum Silver/Thin & Light- 1.59kg']

In [55]:
print(len(titles[:10]),len(ratings[:10]),len(prices[:10]))

10 10 10

In [56]:
df=pd.DataFrame({'Titles':titles[:10],'Ratings':ratings[:10],'Prices':prices[:10]})
df

                                              Titles Ratings    Prices
0  Lenovo IdeaPad Slim 3 Intel Core i7 12th Gen 1...     459    69,990
1  MSI Modern 14, Intel 12th Gen. i7-1255U, 36CM ...      87    62,990
2  MSI Modern 14, Intel 12th Gen. i7-1255U, 36CM ...      87    49,990
3  ASUS TUF Gaming F15, 15.6"(39.62 cms) FHD 144H...     226    49,990
4  Acer Travelmate Business Laptop Intel Core i7-...       2    74,990
5  Lenovo Yoga Slim7 Carbon Intel Evo i7 1260P 13...       4    49,990
6  Lenovo IdeaPad Slim 3 Intel Core i7 12th Gen 1...     459  1,19,990
7  HP Pavilion X360 11th Gen Intel Core i7 14" (3...     226    62,990
8  ASUS Vivobook 15, Intel Core i7-12650H 12th Ge...     231    69,990
9  Dell Inspiron 5430 Laptop, 13th Gen Intel Core...          1,39,990

Q6: Write a python program to scrape data for Top 1000 Quotes of All Time.
The above task will be done in following steps:
1. First get the webpagehttps://www.azquotes.com/
2. Click on TopQuote
3. Than scrap a)Quote b) Author c) Type Of Quotes

In [57]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By

In [58]:
driver=webdriver.Chrome()

In [60]:
driver.get('https://www.azquotes.com/')

In [62]:
topquotes=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/div[1]/div/div[3]/ul/li[5]/a')
topquotes.click()

In [63]:
quote=[]
author=[]
qtype=[]

In [71]:
for page in range(1,10):
 quotes=driver.find_elements(By.XPATH,'//a[@class="title"]')
 authors=driver.find_elements(By.XPATH,'//div[@class="author"]/a')
 qtypes=driver.find_elements(By.XPATH,'//div[@class="tags"]')

 for i in quotes:
    quote.append(i.text)
    quote[:1000]
    
 for i in authors:
    author.append(i.text)
    author[:1000]
    
 for i in qtypes:
    qtype.append(i.text)
    qtype[:1000]

In [72]:
author[:1000]

['Michael Porter',
 'Golda Meir',
 'Theodore Roosevelt',
 'Nelson Mandela',
 'Erma Bombeck',
 'John Wooden',
 'Albert Einstein',
 'Frank Zappa',
 'William Faulkner',
 'Will Rogers',
 'Jimmy Carter',
 'Albert Einstein',
 'Abraham Lincoln',
 'Steven Weinberg',
 'Franklin D. Roosevelt',
 'Albert Einstein',
 'Maya Angelou',
 'Mark Twain',
 'Theodore Roosevelt',
 'Michael Jackson',
 'Martin Luther King, Jr.',
 'C. S. Lewis',
 'Theodore Roosevelt',
 'Mark Twain',
 'Abraham Lincoln',
 'Ruth Graham',
 'C. S. Lewis',
 'Groucho Marx',
 'John Lennon',
 'Barbara Bush',
 'Albert Einstein',
 'Francis Chan',
 'Henry Ford',
 'Victor Hugo',
 'Abu Bakr',
 'Zig Ziglar',
 'Winston Churchill',
 'Zig Ziglar',
 'John F. Kennedy',
 'Dwight D. Eisenhower',
 'Winston Churchill',
 'Albert Einstein',
 'Willie Nelson',
 'Johnny Cash',
 'Marie Curie',
 'Maya Angelou',
 'Amy Bloom',
 'Zig Ziglar',
 'John Lennon',
 'Thomas Sowell',
 'Max Lucado',
 'Martin Luther King, Jr.',
 'Thomas Sowell',
 'Salma Hayek',
 'Martin Luther King, Jr.',
 'Douglas MacArthur',
 'Douglas MacArthur',
 'George S. Patton',
 'Corrie Ten Boom',
 'Jim Courier',
 'Zig Ziglar',
 'Edgar Allan Poe',
 'Zig Ziglar',
 'Stephen Covey',
 'Pablo Neruda',
 'Joe Frazier',
 'Bill Cosby',
 'Lewis Grizzard',
 'Les Brown',
 'Meister Eckhart',
 'Muhammad Ali',
 'John C. Maxwell',
 'Thomas A. Edison',
 'Rose Kennedy',
 'Neil Armstrong',
 'Martin Luther',
 'Ronald Reagan',
 'Andrew Murray',
 'Arianna Huffington',
 'Anne Frank',
 'Corrie Ten Boom',
 'Nelson Mandela',
 'Robin Williams',
 'Walt Disney',
 'John F. Kennedy',
 'Mark Twain',
 'John Stott',
 'Wayne Dyer',
 'Steve Jobs',
 'Maya Angelou',
 'Satchel Paige',
 'Mwai Kibaki',
 'Roald Dahl',
 'Robert H. Schuller',
 'Bill Vaughan',
 'Hunter S. Thompson',
 'Corrie Ten Boom',
 'Dalai Lama',
 'Mother Teresa',
 'Norman Vincent Peale',
 'Michael Porter',
 'Golda Meir',
 'Theodore Roosevelt',
 'Nelson Mandela',
 'Erma Bombeck',
 'John Wooden',
 'Albert Einstein',
 'Frank Zappa',
 'William Faulkner',
 'Will Rogers',
 'Jimmy Carter',
 'Albert Einstein',
 'Abraham Lincoln',
 'Steven Weinberg',
 'Franklin D. Roosevelt',
 'Albert Einstein',
 'Maya Angelou',
 'Mark Twain',
 'Theodore Roosevelt',
 'Michael Jackson',
 'Martin Luther King, Jr.',
 'C. S. Lewis',
 'Theodore Roosevelt',
 'Mark Twain',
 'Abraham Lincoln',
 'Ruth Graham',
 'C. S. Lewis',
 'Groucho Marx',
 'John Lennon',
 'Barbara Bush',
 'Albert Einstein',
 'Francis Chan',
 'Henry Ford',
 'Victor Hugo',
 'Abu Bakr',
 'Zig Ziglar',
 'Winston Churchill',
 'Zig Ziglar',
 'John F. Kennedy',
 'Dwight D. Eisenhower',
 'Winston Churchill',
 'Albert Einstein',
 'Willie Nelson',
 'Johnny Cash',
 'Marie Curie',
 'Maya Angelou',
 'Amy Bloom',
 'Zig Ziglar',
 'John Lennon',
 'Thomas Sowell',
 'Max Lucado',
 'Martin Luther King, Jr.',
 'Thomas Sowell',
 'Salma Hayek',
 'Martin Luther King, Jr.',
 'Douglas MacArthur',
 'Douglas MacArthur',
 'George S. Patton',
 'Corrie Ten Boom',
 'Jim Courier',
 'Zig Ziglar',
 'Edgar Allan Poe',
 'Zig Ziglar',
 'Stephen Covey',
 'Pablo Neruda',
 'Joe Frazier',
 'Bill Cosby',
 'Lewis Grizzard',
 'Les Brown',
 'Meister Eckhart',
 'Muhammad Ali',
 'John C. Maxwell',
 'Thomas A. Edison',
 'Rose Kennedy',
 'Neil Armstrong',
 'Martin Luther',
 'Ronald Reagan',
 'Andrew Murray',
 'Arianna Huffington',
 'Anne Frank',
 'Corrie Ten Boom',
 'Nelson Mandela',
 'Robin Williams',
 'Walt Disney',
 'John F. Kennedy',
 'Mark Twain',
 'John Stott',
 'Wayne Dyer',
 'Steve Jobs',
 'Maya Angelou',
 'Satchel Paige',
 'Mwai Kibaki',
 'Roald Dahl',
 'Robert H. Schuller',
 'Bill Vaughan',
 'Hunter S. Thompson',
 'Corrie Ten Boom',
 'Dalai Lama',
 'Mother Teresa',
 'Norman Vincent Peale',
 'Michael Porter',
 'Golda Meir',
 'Theodore Roosevelt',
 'Nelson Mandela',
 'Erma Bombeck',
 'John Wooden',
 'Albert Einstein',
 'Frank Zappa',
 'William Faulkner',
 'Will Rogers',
 'Jimmy Carter',
 'Albert Einstein',
 'Abraham Lincoln',
 'Steven Weinberg',
 'Franklin D. Roosevelt',
 'Albert Einstein',
 'Maya Angelou',
 'Mark Twain',
 'Theodore Roosevelt',
 'Michael Jackson',
 'Martin Luther King, Jr.',
 'C. S. Lewis',
 'Theodore Roosevelt',
 'Mark Twain',
 'Abraham Lincoln',
 'Ruth Graham',
 'C. S. Lewis',
 'Groucho Marx',
 'John Lennon',
 'Barbara Bush',
 'Albert Einstein',
 'Francis Chan',
 'Henry Ford',
 'Victor Hugo',
 'Abu Bakr',
 'Zig Ziglar',
 'Winston Churchill',
 'Zig Ziglar',
 'John F. Kennedy',
 'Dwight D. Eisenhower',
 'Winston Churchill',
 'Albert Einstein',
 'Willie Nelson',
 'Johnny Cash',
 'Marie Curie',
 'Maya Angelou',
 'Amy Bloom',
 'Zig Ziglar',
 'John Lennon',
 'Thomas Sowell',
 'Max Lucado',
 'Martin Luther King, Jr.',
 'Thomas Sowell',
 'Salma Hayek',
 'Martin Luther King, Jr.',
 'Douglas MacArthur',
 'Douglas MacArthur',
 'George S. Patton',
 'Corrie Ten Boom',
 'Jim Courier',
 'Zig Ziglar',
 'Edgar Allan Poe',
 'Zig Ziglar',
 'Stephen Covey',
 'Pablo Neruda',
 'Joe Frazier',
 'Bill Cosby',
 'Lewis Grizzard',
 'Les Brown',
 'Meister Eckhart',
 'Muhammad Ali',
 'John C. Maxwell',
 'Thomas A. Edison',
 'Rose Kennedy',
 'Neil Armstrong',
 'Martin Luther',
 'Ronald Reagan',
 'Andrew Murray',
 'Arianna Huffington',
 'Anne Frank',
 'Corrie Ten Boom',
 'Nelson Mandela',
 'Robin Williams',
 'Walt Disney',
 'John F. Kennedy',
 'Mark Twain',
 'John Stott',
 'Wayne Dyer',
 'Steve Jobs',
 'Maya Angelou',
 'Satchel Paige',
 'Mwai Kibaki',
 'Roald Dahl',
 'Robert H. Schuller',
 'Bill Vaughan',
 'Hunter S. Thompson',
 'Corrie Ten Boom',
 'Dalai Lama',
 'Mother Teresa',
 'Norman Vincent Peale',
 'Michael Porter',
 'Golda Meir',
 'Theodore Roosevelt',
 'Nelson Mandela',
 'Erma Bombeck',
 'John Wooden',
 'Albert Einstein',
 'Frank Zappa',
 'William Faulkner',
 'Will Rogers',
 'Jimmy Carter',
 'Albert Einstein',
 'Abraham Lincoln',
 'Steven Weinberg',
 'Franklin D. Roosevelt',
 'Albert Einstein',
 'Maya Angelou',
 'Mark Twain',
 'Theodore Roosevelt',
 'Michael Jackson',
 'Martin Luther King, Jr.',
 'C. S. Lewis',
 'Theodore Roosevelt',
 'Mark Twain',
 'Abraham Lincoln',
 'Ruth Graham',
 'C. S. Lewis',
 'Groucho Marx',
 'John Lennon',
 'Barbara Bush',
 'Albert Einstein',
 'Francis Chan',
 'Henry Ford',
 'Victor Hugo',
 'Abu Bakr',
 'Zig Ziglar',
 'Winston Churchill',
 'Zig Ziglar',
 'John F. Kennedy',
 'Dwight D. Eisenhower',
 'Winston Churchill',
 'Albert Einstein',
 'Willie Nelson',
 'Johnny Cash',
 'Marie Curie',
 'Maya Angelou',
 'Amy Bloom',
 'Zig Ziglar',
 'John Lennon',
 'Thomas Sowell',
 'Max Lucado',
 'Martin Luther King, Jr.',
 'Thomas Sowell',
 'Salma Hayek',
 'Martin Luther King, Jr.',
 'Douglas MacArthur',
 'Douglas MacArthur',
 'George S. Patton',
 'Corrie Ten Boom',
 'Jim Courier',
 'Zig Ziglar',
 'Edgar Allan Poe',
 'Zig Ziglar',
 'Stephen Covey',
 'Pablo Neruda',
 'Joe Frazier',
 'Bill Cosby',
 'Lewis Grizzard',
 'Les Brown',
 'Meister Eckhart',
 'Muhammad Ali',
 'John C. Maxwell',
 'Thomas A. Edison',
 'Rose Kennedy',
 'Neil Armstrong',
 'Martin Luther',
 'Ronald Reagan',
 'Andrew Murray',
 'Arianna Huffington',
 'Anne Frank',
 'Corrie Ten Boom',
 'Nelson Mandela',
 'Robin Williams',
 'Walt Disney',
 'John F. Kennedy',
 'Mark Twain',
 'John Stott',
 'Wayne Dyer',
 'Steve Jobs',
 'Maya Angelou',
 'Satchel Paige',
 'Mwai Kibaki',
 'Roald Dahl',
 'Robert H. Schuller',
 'Bill Vaughan',
 'Hunter S. Thompson',
 'Corrie Ten Boom',
 'Dalai Lama',
 'Mother Teresa',
 'Norman Vincent Peale',
 'Michael Porter',
 'Golda Meir',
 'Theodore Roosevelt',
 'Nelson Mandela',
 'Erma Bombeck',
 'John Wooden',
 'Albert Einstein',
 'Frank Zappa',
 'William Faulkner',
 'Will Rogers',
 'Jimmy Carter',
 'Albert Einstein',
 'Abraham Lincoln',
 'Steven Weinberg',
 'Franklin D. Roosevelt',
 'Albert Einstein',
 'Maya Angelou',
 'Mark Twain',
 'Theodore Roosevelt',
 'Michael Jackson',
 'Martin Luther King, Jr.',
 'C. S. Lewis',
 'Theodore Roosevelt',
 'Mark Twain',
 'Abraham Lincoln',
 'Ruth Graham',
 'C. S. Lewis',
 'Groucho Marx',
 'John Lennon',
 'Barbara Bush',
 'Albert Einstein',
 'Francis Chan',
 'Henry Ford',
 'Victor Hugo',
 'Abu Bakr',
 'Zig Ziglar',
 'Winston Churchill',
 'Zig Ziglar',
 'John F. Kennedy',
 'Dwight D. Eisenhower',
 'Winston Churchill',
 'Albert Einstein',
 'Willie Nelson',
 'Johnny Cash',
 'Marie Curie',
 'Maya Angelou',
 'Amy Bloom',
 'Zig Ziglar',
 'John Lennon',
 'Thomas Sowell',
 'Max Lucado',
 'Martin Luther King, Jr.',
 'Thomas Sowell',
 'Salma Hayek',
 'Martin Luther King, Jr.',
 'Douglas MacArthur',
 'Douglas MacArthur',
 'George S. Patton',
 'Corrie Ten Boom',
 'Jim Courier',
 'Zig Ziglar',
 'Edgar Allan Poe',
 'Zig Ziglar',
 'Stephen Covey',
 'Pablo Neruda',
 'Joe Frazier',
 'Bill Cosby',
 'Lewis Grizzard',
 'Les Brown',
 'Meister Eckhart',
 'Muhammad Ali',
 'John C. Maxwell',
 'Thomas A. Edison',
 'Rose Kennedy',
 'Neil Armstrong',
 'Martin Luther',
 'Ronald Reagan',
 'Andrew Murray',
 'Arianna Huffington',
 'Anne Frank',
 'Corrie Ten Boom',
 'Nelson Mandela',
 'Robin Williams',
 'Walt Disney',
 'John F. Kennedy',
 'Mark Twain',
 'John Stott',
 'Wayne Dyer',
 'Steve Jobs',
 'Maya Angelou',
 'Satchel Paige',
 'Mwai Kibaki',
 'Roald Dahl',
 'Robert H. Schuller',
 'Bill Vaughan',
 'Hunter S. Thompson',
 'Corrie Ten Boom',
 'Dalai Lama',
 'Mother Teresa',
 'Norman Vincent Peale',
 'Michael Porter',
 'Golda Meir',
 'Theodore Roosevelt',
 'Nelson Mandela',
 'Erma Bombeck',
 'John Wooden',
 'Albert Einstein',
 'Frank Zappa',
 'William Faulkner',
 'Will Rogers',
 'Jimmy Carter',
 'Albert Einstein',
 'Abraham Lincoln',
 'Steven Weinberg',
 'Franklin D. Roosevelt',
 'Albert Einstein',
 'Maya Angelou',
 'Mark Twain',
 'Theodore Roosevelt',
 'Michael Jackson',
 'Martin Luther King, Jr.',
 'C. S. Lewis',
 'Theodore Roosevelt',
 'Mark Twain',
 'Abraham Lincoln',
 'Ruth Graham',
 'C. S. Lewis',
 'Groucho Marx',
 'John Lennon',
 'Barbara Bush',
 'Albert Einstein',
 'Francis Chan',
 'Henry Ford',
 'Victor Hugo',
 'Abu Bakr',
 'Zig Ziglar',
 'Winston Churchill',
 'Zig Ziglar',
 'John F. Kennedy',
 'Dwight D. Eisenhower',
 'Winston Churchill',
 'Albert Einstein',
 'Willie Nelson',
 'Johnny Cash',
 'Marie Curie',
 'Maya Angelou',
 'Amy Bloom',
 'Zig Ziglar',
 'John Lennon',
 'Thomas Sowell',
 'Max Lucado',
 'Martin Luther King, Jr.',
 'Thomas Sowell',
 'Salma Hayek',
 'Martin Luther King, Jr.',
 'Douglas MacArthur',
 'Douglas MacArthur',
 'George S. Patton',
 'Corrie Ten Boom',
 'Jim Courier',
 'Zig Ziglar',
 'Edgar Allan Poe',
 'Zig Ziglar',
 'Stephen Covey',
 'Pablo Neruda',
 'Joe Frazier',
 'Bill Cosby',
 'Lewis Grizzard',
 'Les Brown',
 'Meister Eckhart',
 'Muhammad Ali',
 'John C. Maxwell',
 'Thomas A. Edison',
 'Rose Kennedy',
 'Neil Armstrong',
 'Martin Luther',
 'Ronald Reagan',
 'Andrew Murray',
 'Arianna Huffington',
 'Anne Frank',
 'Corrie Ten Boom',
 'Nelson Mandela',
 'Robin Williams',
 'Walt Disney',
 'John F. Kennedy',
 'Mark Twain',
 'John Stott',
 'Wayne Dyer',
 'Steve Jobs',
 'Maya Angelou',
 'Satchel Paige',
 'Mwai Kibaki',
 'Roald Dahl',
 'Robert H. Schuller',
 'Bill Vaughan',
 'Hunter S. Thompson',
 'Corrie Ten Boom',
 'Dalai Lama',
 'Mother Teresa',
 'Norman Vincent Peale',
 'Michael Porter',
 'Golda Meir',
 'Theodore Roosevelt',
 'Nelson Mandela',
 'Erma Bombeck',
 'John Wooden',
 'Albert Einstein',
 'Frank Zappa',
 'William Faulkner',
 'Will Rogers',
 'Jimmy Carter',
 'Albert Einstein',
 'Abraham Lincoln',
 'Steven Weinberg',
 'Franklin D. Roosevelt',
 'Albert Einstein',
 'Maya Angelou',
 'Mark Twain',
 'Theodore Roosevelt',
 'Michael Jackson',
 'Martin Luther King, Jr.',
 'C. S. Lewis',
 'Theodore Roosevelt',
 'Mark Twain',
 'Abraham Lincoln',
 'Ruth Graham',
 'C. S. Lewis',
 'Groucho Marx',
 'John Lennon',
 'Barbara Bush',
 'Albert Einstein',
 'Francis Chan',
 'Henry Ford',
 'Victor Hugo',
 'Abu Bakr',
 'Zig Ziglar',
 'Winston Churchill',
 'Zig Ziglar',
 'John F. Kennedy',
 'Dwight D. Eisenhower',
 'Winston Churchill',
 'Albert Einstein',
 'Willie Nelson',
 'Johnny Cash',
 'Marie Curie',
 'Maya Angelou',
 'Amy Bloom',
 'Zig Ziglar',
 'John Lennon',
 'Thomas Sowell',
 'Max Lucado',
 'Martin Luther King, Jr.',
 'Thomas Sowell',
 'Salma Hayek',
 'Martin Luther King, Jr.',
 'Douglas MacArthur',
 'Douglas MacArthur',
 'George S. Patton',
 'Corrie Ten Boom',
 'Jim Courier',
 'Zig Ziglar',
 'Edgar Allan Poe',
 'Zig Ziglar',
 'Stephen Covey',
 'Pablo Neruda',
 'Joe Frazier',
 'Bill Cosby',
 'Lewis Grizzard',
 'Les Brown',
 'Meister Eckhart',
 'Muhammad Ali',
 'John C. Maxwell',
 'Thomas A. Edison',
 'Rose Kennedy',
 'Neil Armstrong',
 'Martin Luther',
 'Ronald Reagan',
 'Andrew Murray',
 'Arianna Huffington',
 'Anne Frank',
 'Corrie Ten Boom',
 'Nelson Mandela',
 'Robin Williams',
 'Walt Disney',
 'John F. Kennedy',
 'Mark Twain',
 'John Stott',
 'Wayne Dyer',
 'Steve Jobs',
 'Maya Angelou',
 'Satchel Paige',
 'Mwai Kibaki',
 'Roald Dahl',
 'Robert H. Schuller',
 'Bill Vaughan',
 'Hunter S. Thompson',
 'Corrie Ten Boom',
 'Dalai Lama',
 'Mother Teresa',
 'Norman Vincent Peale',
 'Michael Porter',
 'Golda Meir',
 'Theodore Roosevelt',
 'Nelson Mandela',
 'Erma Bombeck',
 'John Wooden',
 'Albert Einstein',
 'Frank Zappa',
 'William Faulkner',
 'Will Rogers',
 'Jimmy Carter',
 'Albert Einstein',
 'Abraham Lincoln',
 'Steven Weinberg',
 'Franklin D. Roosevelt',
 'Albert Einstein',
 'Maya Angelou',
 'Mark Twain',
 'Theodore Roosevelt',
 'Michael Jackson',
 'Martin Luther King, Jr.',
 'C. S. Lewis',
 'Theodore Roosevelt',
 'Mark Twain',
 'Abraham Lincoln',
 'Ruth Graham',
 'C. S. Lewis',
 'Groucho Marx',
 'John Lennon',
 'Barbara Bush',
 'Albert Einstein',
 'Francis Chan',
 'Henry Ford',
 'Victor Hugo',
 'Abu Bakr',
 'Zig Ziglar',
 'Winston Churchill',
 'Zig Ziglar',
 'John F. Kennedy',
 'Dwight D. Eisenhower',
 'Winston Churchill',
 'Albert Einstein',
 'Willie Nelson',
 'Johnny Cash',
 'Marie Curie',
 'Maya Angelou',
 'Amy Bloom',
 'Zig Ziglar',
 'John Lennon',
 'Thomas Sowell',
 'Max Lucado',
 'Martin Luther King, Jr.',
 'Thomas Sowell',
 'Salma Hayek',
 'Martin Luther King, Jr.',
 'Douglas MacArthur',
 'Douglas MacArthur',
 'George S. Patton',
 'Corrie Ten Boom',
 'Jim Courier',
 'Zig Ziglar',
 'Edgar Allan Poe',
 'Zig Ziglar',
 'Stephen Covey',
 'Pablo Neruda',
 'Joe Frazier',
 'Bill Cosby',
 'Lewis Grizzard',
 'Les Brown',
 'Meister Eckhart',
 'Muhammad Ali',
 'John C. Maxwell',
 'Thomas A. Edison',
 'Rose Kennedy',
 'Neil Armstrong',
 'Martin Luther',
 'Ronald Reagan',
 'Andrew Murray',
 'Arianna Huffington',
 'Anne Frank',
 'Corrie Ten Boom',
 'Nelson Mandela',
 'Robin Williams',
 'Walt Disney',
 'John F. Kennedy',
 'Mark Twain',
 'John Stott',
 'Wayne Dyer',
 'Steve Jobs',
 'Maya Angelou',
 'Satchel Paige',
 'Mwai Kibaki',
 'Roald Dahl',
 'Robert H. Schuller',
 'Bill Vaughan',
 'Hunter S. Thompson',
 'Corrie Ten Boom',
 'Dalai Lama',
 'Mother Teresa',
 'Norman Vincent Peale',
 'Michael Porter',
 'Golda Meir',
 'Theodore Roosevelt',
 'Nelson Mandela',
 'Erma Bombeck',
 'John Wooden',
 'Albert Einstein',
 'Frank Zappa',
 'William Faulkner',
 'Will Rogers',
 'Jimmy Carter',
 'Albert Einstein',
 'Abraham Lincoln',
 'Steven Weinberg',
 'Franklin D. Roosevelt',
 'Albert Einstein',
 'Maya Angelou',
 'Mark Twain',
 'Theodore Roosevelt',
 'Michael Jackson',
 'Martin Luther King, Jr.',
 'C. S. Lewis',
 'Theodore Roosevelt',
 'Mark Twain',
 'Abraham Lincoln',
 'Ruth Graham',
 'C. S. Lewis',
 'Groucho Marx',
 'John Lennon',
 'Barbara Bush',
 'Albert Einstein',
 'Francis Chan',
 'Henry Ford',
 'Victor Hugo',
 'Abu Bakr',
 'Zig Ziglar',
 'Winston Churchill',
 'Zig Ziglar',
 'John F. Kennedy',
 'Dwight D. Eisenhower',
 'Winston Churchill',
 'Albert Einstein',
 'Willie Nelson',
 'Johnny Cash',
 'Marie Curie',
 'Maya Angelou',
 'Amy Bloom',
 'Zig Ziglar',
 'John Lennon',
 'Thomas Sowell',
 'Max Lucado',
 'Martin Luther King, Jr.',
 'Thomas Sowell',
 'Salma Hayek',
 'Martin Luther King, Jr.',
 'Douglas MacArthur',
 'Douglas MacArthur',
 'George S. Patton',
 'Corrie Ten Boom',
 'Jim Courier',
 'Zig Ziglar',
 'Edgar Allan Poe',
 'Zig Ziglar',
 'Stephen Covey',
 'Pablo Neruda',
 'Joe Frazier',
 'Bill Cosby',
 'Lewis Grizzard',
 'Les Brown',
 'Meister Eckhart',
 'Muhammad Ali',
 'John C. Maxwell',
 'Thomas A. Edison',
 'Rose Kennedy',
 'Neil Armstrong',
 'Martin Luther',
 'Ronald Reagan',
 'Andrew Murray',
 'Arianna Huffington',
 'Anne Frank',
 'Corrie Ten Boom',
 'Nelson Mandela',
 'Robin Williams',
 'Walt Disney',
 'John F. Kennedy',
 'Mark Twain',
 'John Stott',
 'Wayne Dyer',
 'Steve Jobs',
 'Maya Angelou',
 'Satchel Paige',
 'Mwai Kibaki',
 'Roald Dahl',
 'Robert H. Schuller',
 'Bill Vaughan',
 'Hunter S. Thompson',
 'Corrie Ten Boom',
 'Dalai Lama',
 'Mother Teresa',
 'Norman Vincent Peale',
 'Michael Porter',
 'Golda Meir',
 'Theodore Roosevelt',
 'Nelson Mandela',
 'Erma Bombeck',
 'John Wooden',
 'Albert Einstein',
 'Frank Zappa',
 'William Faulkner',
 'Will Rogers',
 'Jimmy Carter',
 'Albert Einstein',
 'Abraham Lincoln',
 'Steven Weinberg',
 'Franklin D. Roosevelt',
 'Albert Einstein',
 'Maya Angelou',
 'Mark Twain',
 'Theodore Roosevelt',
 'Michael Jackson',
 'Martin Luther King, Jr.',
 'C. S. Lewis',
 'Theodore Roosevelt',
 'Mark Twain',
 'Abraham Lincoln',
 'Ruth Graham',
 'C. S. Lewis',
 'Groucho Marx',
 'John Lennon',
 'Barbara Bush',
 'Albert Einstein',
 'Francis Chan',
 'Henry Ford',
 'Victor Hugo',
 'Abu Bakr',
 'Zig Ziglar',
 'Winston Churchill',
 'Zig Ziglar',
 'John F. Kennedy',
 'Dwight D. Eisenhower',
 'Winston Churchill',
 'Albert Einstein',
 'Willie Nelson',
 'Johnny Cash',
 'Marie Curie',
 'Maya Angelou',
 'Amy Bloom',
 'Zig Ziglar',
 'John Lennon',
 'Thomas Sowell',
 'Max Lucado',
 'Martin Luther King, Jr.',
 'Thomas Sowell',
 'Salma Hayek',
 'Martin Luther King, Jr.',
 'Douglas MacArthur',
 'Douglas MacArthur',
 'George S. Patton',
 'Corrie Ten Boom',
 'Jim Courier',
 'Zig Ziglar',
 'Edgar Allan Poe',
 'Zig Ziglar',
 'Stephen Covey',
 'Pablo Neruda',
 'Joe Frazier',
 'Bill Cosby',
 'Lewis Grizzard',
 'Les Brown',
 'Meister Eckhart',
 'Muhammad Ali',
 'John C. Maxwell',
 'Thomas A. Edison',
 'Rose Kennedy',
 'Neil Armstrong',
 'Martin Luther',
 'Ronald Reagan',
 'Andrew Murray',
 'Arianna Huffington',
 'Anne Frank',
 'Corrie Ten Boom',
 'Nelson Mandela',
 'Robin Williams',
 'Walt Disney',
 'John F. Kennedy',
 'Mark Twain',
 'John Stott',
 'Wayne Dyer',
 'Steve Jobs',
 'Maya Angelou',
 'Satchel Paige',
 'Mwai Kibaki',
 'Roald Dahl',
 'Robert H. Schuller',
 'Bill Vaughan',
 'Hunter S. Thompson',
 'Corrie Ten Boom',
 'Dalai Lama',
 'Mother Teresa',
 'Norman Vincent Peale']

In [73]:
print(len(quote[:1000]),len(author[:1000]),len(qtype[:1000]))

1000 1000 1000

In [74]:
df=pd.DataFrame({'Quote':quote[:1000],'Author':author[:1000],'Type of quote':qtype[:1000]})
df

,Quote,Author,Type of quote
0,The essence of strategy is choosing what not t...,Michael Porter,"Essence, Deep Thought, Transcendentalism"
1,One cannot and must not try to erase the past ...,Golda Meir,"Inspiration, Past, Trying"
2,Patriotism means to stand by the country. It d...,Theodore Roosevelt,"Country, Peace, War"
3,Death is something inevitable. When a man has ...,Nelson Mandela,"Inspirational, Motivational, Death"
4,You have to love a nation that celebrates its ...,Erma Bombeck,"4th Of July, Food, Patriotic"
...,...,...,...
995,"When the going gets weird, the weird turn pro.",Hunter S. Thompson,"Music, Sports, Hunting"
996,When a train goes through a tunnel and it gets...,Corrie Ten Boom,"Trust, Encouraging, Uplifting"
997,If you think you are too small to make a diffe...,Dalai Lama,"Inspirational, Funny, Change"
998,"God doesn't require us to succeed, he only req...",Mother Teresa,"Success, God, Mother"
999,Change your thoughts and you change your world.,Norman Vincent Peale,"Inspirational, Motivational, Change"

Q7: Write a python program to display list of respected former Prime Ministers of India (i.e. Name,Born-Dead, Term of office, Remarks) from https://www.jagranjosh.com/general-knowledge/list-of-all-prime-ministers-of-india-1473165149-1
scrap the mentioned data and make the DataFrame

In [4]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By

In [5]:
driver=webdriver.Chrome()

In [6]:
driver.get('https://www.jagranjosh.com/general-knowledge/list-of-all-prime-ministers-of-india-1473165149-1')

In [7]:
PMname=[]
born_dead=[]
term=[]
remark=[]

In [24]:
name=driver.find_elements(By.XPATH,'//div[@class="TableData"]/table/tbody/tr/td[2]/div')
for i in name:
    PMname.append(i.text)
    PMname

In [9]:
PMname

['Jawahar Lal Nehru',
 'Gulzarilal Nanda (Acting)',
 'Lal Bahadur Shastri',
 'Gulzari Lal Nanda  (Acting)',
 'Indira Gandhi',
 'Morarji Desai',
 'Charan Singh',
 'Indira Gandhi',
 'Rajiv Gandhi',
 'V. P. Singh',
 'Chandra Shekhar',
 'P. V. Narasimha Rao',
 'Atal Bihari Vajpayee',
 'H. D. Deve Gowda',
 'Inder Kumar Gujral',
 'Atal Bihari Vajpayee',
 'Manmohan Singh',
 'Narendra Modi',
 'Narendra Modi']

In [25]:
tenure=driver.find_elements(By.XPATH,'//div[@class="TableData"]/table/tbody/tr/td[3]/div')
for i in tenure:
    born_dead.append(i.text)
    born_dead

In [30]:
born_dead

['(1889–1964)',
 '(1898-1998)',
 '(1904–1966)',
 '(1898-1998)',
 '(1917–1984)',
 '(1896–1995)',
 '(1902–1987)',
 '(1917–1984)',
 '(1944–1991)',
 '(1931–2008)',
 '(1927–2007)',
 '(1921–2004)',
 '(1924- 2018)',
 '(born 1933)',
 '(1919–2012)',
 '(1924-2018)',
 '(born 1932)',
 '(born 1950)',
 '(born 1950)',
 '(1889–1964)',
 '(1898-1998)',
 '(1904–1966)',
 '(1898-1998)',
 '(1917–1984)',
 '(1896–1995)',
 '(1902–1987)',
 '(1917–1984)',
 '(1944–1991)',
 '(1931–2008)',
 '(1927–2007)',
 '(1921–2004)',
 '(1924- 2018)',
 '(born 1933)',
 '(1919–2012)',
 '(1924-2018)',
 '(born 1932)',
 '(born 1950)',
 '(born 1950)']

In [26]:
term_office=driver.find_elements(By.XPATH,'//div[@class="TableData"]/table/tbody/tr/td[4]')
for i in term_office:
    term.append(i.text)
    term

In [31]:
term

['15 August 1947 to 27 May 1964\n16 years, 286 days',
 '27 May 1964 to 9 June 1964,\n13 days',
 '9 June 1964 to 11 January 1966\n1 year, 216 days',
 '11 January 1966 to 24 January 1966\n13 days',
 '24 January 1966 to 24 March 1977\n11 years, 59 days',
 '24 March 1977 to  28 July 1979 \n2 year, 126 days',
 '28 July 1979 to 14 January 1980\n170 days',
 '14 January 1980 to 31 October 1984\n4 years, 291 days',
 '31 October 1984 to 2 December 1989\n5 years, 32 days',
 '2 December 1989 to 10 November 1990\n343 days',
 '10 November 1990 to 21 June 1991\n223 days',
 '21 June 1991 to 16 May 1996\n4 years, 330 days',
 '16 May 1996 to 1 June 1996\n16 days',
 '1 June 1996 to 21 April 1997\n324 days',
 '21 April 1997 to 19 March 1998 \n332 days',
 '19 March 1998 to 22 May 2004 \n6 years, 64 days',
 '22 May 2004 to 26 May 2014   \n10 years, 4 days',
 '26 May 2014 - 2019',
 '30 May 2019- Incumbent',
 '15 August 1947 to 27 May 1964\n16 years, 286 days',
 '27 May 1964 to 9 June 1964,\n13 days',
 '9 June 1964 to 11 January 1966\n1 year, 216 days',
 '11 January 1966 to 24 January 1966\n13 days',
 '24 January 1966 to 24 March 1977\n11 years, 59 days',
 '24 March 1977 to  28 July 1979 \n2 year, 126 days',
 '28 July 1979 to 14 January 1980\n170 days',
 '14 January 1980 to 31 October 1984\n4 years, 291 days',
 '31 October 1984 to 2 December 1989\n5 years, 32 days',
 '2 December 1989 to 10 November 1990\n343 days',
 '10 November 1990 to 21 June 1991\n223 days',
 '21 June 1991 to 16 May 1996\n4 years, 330 days',
 '16 May 1996 to 1 June 1996\n16 days',
 '1 June 1996 to 21 April 1997\n324 days',
 '21 April 1997 to 19 March 1998 \n332 days',
 '19 March 1998 to 22 May 2004 \n6 years, 64 days',
 '22 May 2004 to 26 May 2014   \n10 years, 4 days',
 '26 May 2014 - 2019',
 '30 May 2019- Incumbent']

In [27]:
remarks=driver.find_elements(By.XPATH,'//div[@class="TableData"]/table/tbody/tr/td[5]/div')
for i in remarks:
    remark.append(i.text)
    remark

In [34]:
remark

[<selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.122")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.123")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.124")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.125")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.126")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.127")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.128")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.129")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.130")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.131")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.132")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.133")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.134")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.135")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.136")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.137")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.138")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.139")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e2302885cb93e978c5912ace1efe5c14", element="f.3E72B54B0780BE48DA8313D71513352B.d.BE5FBD047B0E762C9C4A1E8C5650A88C.e.140")>,
 'The first prime minister of India and the longest-serving PM of India, the first to die in office.',
 'First acting PM of India',
 "He has given the slogan of 'Jai Jawan Jai Kisan' during the Indo-Pak war of 1965",
 '-',
 'First female Prime Minister of India',
 'Oldest to become PM (81 years old) and first to resign from office',
 'Only PM who did not face the Parliament',
 'The first lady who served as PM for the second term',
 'Youngest to become PM (40 years old)',
 'First PM to step down after a vote of no confidence',
 'He belongs to  Samajwadi Janata Party',
 'First PM from South India',
 'PM for shortest tenure',
 'He belongs to  Janata Dal',
 '------',
 ' The first non-congress PM who completed a full term as PM',
 ' First Sikh PM',
 '4th Prime Minister of India who served two consecutive tenures',
 'First non-congress PM with two consecutive tenures',
 'The first prime minister of India and the longest-serving PM of India, the first to die in office.',
 'First acting PM of India',
 "He has given the slogan of 'Jai Jawan Jai Kisan' during the Indo-Pak war of 1965",
 '-',
 'First female Prime Minister of India',
 'Oldest to become PM (81 years old) and first to resign from office',
 'Only PM who did not face the Parliament',
 'The first lady who served as PM for the second term',
 'Youngest to become PM (40 years old)',
 'First PM to step down after a vote of no confidence',
 'He belongs to  Samajwadi Janata Party',
 'First PM from South India',
 'PM for shortest tenure',
 'He belongs to  Janata Dal',
 '------',
 ' The first non-congress PM who completed a full term as PM',
 ' First Sikh PM',
 '4th Prime Minister of India who served two consecutive tenures',
 'First non-congress PM with two consecutive tenures',
 'The first prime minister of India and the longest-serving PM of India, the first to die in office.',
 'First acting PM of India',
 "He has given the slogan of 'Jai Jawan Jai Kisan' during the Indo-Pak war of 1965",
 '-',
 'First female Prime Minister of India',
 'Oldest to become PM (81 years old) and first to resign from office',
 'Only PM who did not face the Parliament',
 'The first lady who served as PM for the second term',
 'Youngest to become PM (40 years old)',
 'First PM to step down after a vote of no confidence',
 'He belongs to  Samajwadi Janata Party',
 'First PM from South India',
 'PM for shortest tenure',
 'He belongs to  Janata Dal',
 '------',
 ' The first non-congress PM who completed a full term as PM',
 ' First Sikh PM',
 '4th Prime Minister of India who served two consecutive tenures',
 'First non-congress PM with two consecutive tenures',
 'The first prime minister of India and the longest-serving PM of India, the first to die in office.',
 'First acting PM of India',
 "He has given the slogan of 'Jai Jawan Jai Kisan' during the Indo-Pak war of 1965",
 '-',
 'First female Prime Minister of India',
 'Oldest to become PM (81 years old) and first to resign from office',
 'Only PM who did not face the Parliament',
 'The first lady who served as PM for the second term',
 'Youngest to become PM (40 years old)',
 'First PM to step down after a vote of no confidence',
 'He belongs to  Samajwadi Janata Party',
 'First PM from South India',
 'PM for shortest tenure',
 'He belongs to  Janata Dal',
 '------',
 ' The first non-congress PM who completed a full term as PM',
 ' First Sikh PM',
 '4th Prime Minister of India who served two consecutive tenures',
 'First non-congress PM with two consecutive tenures']

In [36]:
print(len(PMname),len(born_dead),len(term),len(remark))

38 38 38 95

In [29]:
df=pd.DataFrame({'PM name':PMname,'Born Dead':born_dead,'Term of office':term,'Remark':remark})
df

ValueError: All arrays must be of the same length

Q8: Write a python program to display list of 50 Most expensive cars in the world
(i.e. Car name and Price) from https://www.motor1.com/
This task will be done in following steps:
1. First get the webpage https://www.motor1.com/
2. Then You have to type in the search bar ’50 most expensive cars’
3. Then click on 50 most expensive carsin the world..
4. Then scrap thementioned data and make the dataframe

In [1]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By

In [2]:
driver=webdriver.Chrome()

In [3]:
driver.get('https://www.motor1.com/')

In [5]:
car=driver.find_element(By.XPATH,'/html/body/div[9]/div[2]/div/div/div[3]/div/div/div/form/input')
car.send_keys('50 most expensive cars')

In [7]:
search=driver.find_element(By.XPATH,'/html/body/div[9]/div[2]/div/div/div[3]/div/div/div/form/button[1]')
search.click()

In [8]:
tick=driver.find_element(By.XPATH,'/html/body/div[9]/div[9]/div/div[1]/div/div/div[1]/div/div[1]/h3/a')
tick.click()

In [ ]:
car_name=[]
price=[]
data=[]

In [ ]:
name=driver.find_elements(By.XPATH,'//h3[@class="subheader"]')
for i in name:
    car_name.append(i.text)
    car_name
    
cost=driver.find_elements(By.XPATH,'')
for i in cost:
    price.append(i.text)
    price
    
info=driver.find_elements(By.XPATH,'')
for i in info:
    data.append(i.text)
    data